# Generated by Django 3.2.3 on 2021-06-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancinggroup',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancing_groups', to='sample.company', verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='power_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generator', to='sample.powerplant', verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='balancing_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_plants', to='sample.balancinggroup', verbose_name='名称'),
        ),
    ]
